name: deploy-strapi
on:
  push:
    branches: [ main ] 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: picadelly-backend   
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - run: npm ci
      - run: npm run build
      - run: npm rebuild sharp --platform=linux --arch=x64 || true

      - run: zip -r ../artifact.zip . -x "node_modules/.cache/*"

      - uses: azure/webapps-deploy@v3
        with:
          app-name: YOUR_APP_NAME
          # slot-name: staging          # optional
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: artifact.zip
